AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  DataTable:
    Type: String
    Description: Database table name for storing the birthday
    Default: BirthdayReminder
  Basepath:
    Type: String
    Description: Basepath mapping for custom domain, normally use for API versioning
    Default: v1
Globals:
  Api:
    Name: birthday-reminder
    EndpointConfiguration: REGIONAL
Resources:
  HealthCheckLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/healthCheck
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /healthcheck
            Method: get
  GetPersonLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/getHandler
      Runtime: go1.x
      Tracing: Active
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
            TABLE_NAME: !Ref DataTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: get
  PutPersonLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/putHandler
      Runtime: go1.x
      Tracing: Active
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref DataTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello/{name}
            Method: put
  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !ImportValue 'birthday-gateway-api-certificate'
      DomainName: !ImportValue 'birthday-gateway-api-custom-domain'
      EndpointConfiguration:
        Types:
          - REGIONAL
  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref Basepath
      DomainName: !ImportValue 'birthday-gateway-api-custom-domain'
      RestApiId: !Ref ServerlessRestApi
      Stage: !Ref ServerlessRestApiProdStage
  Healthcheck:
    Type: "AWS::Route53::HealthCheck"
    Properties:
      HealthCheckConfig:
        Port: "443"
        Type: "HTTPS_STR_MATCH"
        SearchString: "ok"
        ResourcePath: "/Prod/healthcheck"
        FullyQualifiedDomainName:
          Fn::Join:
            - ''
            - - !Ref ServerlessRestApi
              - ".execute-api."
              - !Ref AWS::Region
              - .amazonaws.com
        RequestInterval: "30"
        FailureThreshold: "2"
  RegionEndpointRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Region: !Ref AWS::Region
      HealthCheckId: !Ref Healthcheck
      SetIdentifier:
        Fn::Join:
          - ''
          - - 'birthday-endpoint-'
            - !Ref AWS::Region
      HostedZoneId: !ImportValue 'birthday-gateway-api-custom-hosted-zone-id'
      Name: !ImportValue 'birthday-gateway-api-custom-domain'
      Type: CNAME
      TTL: 60
      ResourceRecords:
        - !GetAtt ApiCustomDomain.RegionalDomainName
Outputs:
  URL:
    Description: URL for HTTPS Endpoint
    Value:
      Fn::Join:
        - ''
        - - https://
          - Ref: ServerlessRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - Ref: ServerlessRestApiProdStage
